### ISSUE TITLE
Add temporary merchantId/storeId property into the client API requests

### ISSUE THREAD

**Issue by radobar** [flowup/headlessapis#3]
# Description
We need to identify the store/merchant, that the user is accessing from the client API, for the purpose of retrieval objects associated with a particular merchant, or store.

## Acceptance Criteria
- [x] Data in the requests from the client API can be used to query for a particular merchant/store

**Comment by radobar** [comment]
Hey, @petomalina, we need to identify the store from which the products are retrieved. (for example)
Do you agree with our approach? We plan this to be temporary and the merchant/store identification will later be moved to user's custom claims.

**Comment by petomalina** [comment]
@RadoBart I agree with this approach. We can make this transparent for the client libraries long-term, as engineers of the merchant will be working with them. Tokens will then be internally locked to the merchant/store combination.

**Comment by radobar** [comment]
This has been done as well @vmasek, we kind of skipped over it.
